# Generated by Django 5.2.1 on 2025-05-19 03:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subscription", "0002_paymentreceipt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VPNAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Account ID",
                    ),
                ),
                (
                    "inbound_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="3X-UI Inbound ID"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Email Identifier"
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[("wireguard", "WireGuard")],
                        default="wireguard",
                        max_length=20,
                        verbose_name="Protocol",
                    ),
                ),
                ("port", models.IntegerField(verbose_name="Port Number")),
                (
                    "server_ip",
                    models.CharField(
                        default="116.203.123.232",
                        max_length=50,
                        verbose_name="Server IP",
                    ),
                ),
                (
                    "config_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Configuration Data"
                    ),
                ),
                (
                    "config_file",
                    models.TextField(
                        blank=True, verbose_name="Configuration File Content"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                        ],
                        default="inactive",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_usage_up",
                    models.BigIntegerField(
                        default=0, verbose_name="Upload Data Usage (bytes)"
                    ),
                ),
                (
                    "data_usage_down",
                    models.BigIntegerField(
                        default=0, verbose_name="Download Data Usage (bytes)"
                    ),
                ),
                (
                    "data_limit",
                    models.BigIntegerField(
                        default=0, verbose_name="Data Limit (bytes)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires At"
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vpn_accounts",
                        to="subscription.subscription",
                        verbose_name="Subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vpn_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "VPN Account",
                "verbose_name_plural": "VPN Accounts",
                "ordering": ["-created_at"],
            },
        ),
    ]
