version: '3.8'

services:
  web:
    build: .
    container_name: irip_web
    restart: always
    volumes:
      - ./:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.irip-app.rule=Host(`api.irip.online`)"
      - "traefik.http.routers.irip-app.entrypoints=websecure"
      - "traefik.http.routers.irip-app.tls.certresolver=myresolver"
      - "traefik.http.services.irip-app.loadbalancer.server.port=8000"
    networks:
      - alltogether
  
    extra_hosts:
      - "host.docker.internal:host-gateway"


volumes:
  static_volume:
  media_volume:

networks:
  alltogether:
    external: true
