version: '3.8'

services:
  web:
    build: .
    container_name: irip_web
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn irip.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 120"
  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.irip-app.rule=Host(`api.irip.online`)"
      - "traefik.http.routers.irip-app.entrypoints=websecure"
      - "traefik.http.routers.irip-app.tls.certresolver=myresolver"

volumes:
  static_volume:
  media_volume:
