# Generated by Django 5.2.1 on 2025-05-15 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_invoice_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Stripe Invoice ID"
                    ),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Stripe Charge ID"
                    ),
                ),
                (
                    "amount_paid",
                    models.IntegerField(verbose_name="Amount Paid (in cents)"),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("open", "Open"),
                            ("void", "Void"),
                            ("uncollectible", "Uncollectible"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "invoice_pdf",
                    models.URLField(blank=True, verbose_name="Invoice PDF URL"),
                ),
                (
                    "invoice_url",
                    models.URLField(blank=True, verbose_name="Invoice URL"),
                ),
                ("period_start", models.DateTimeField(verbose_name="Period Start")),
                ("period_end", models.DateTimeField(verbose_name="Period End")),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Payment Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to="subscription.subscription",
                        verbose_name="Subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Receipt",
                "verbose_name_plural": "Payment Receipts",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
    ]
