# Generated by Django 5.2.1 on 2025-05-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_unique_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("not_verified", "Not Verified"),
                    ("email_verified", "Email Verified"),
                    ("security_verified", "Security Verified"),
                ],
                default="not_verified",
                help_text="Know Your Customer verification status",
                max_length=20,
                verbose_name="KYC Status",
            ),
        ),
    ]
